[package]
name = "assembly-theory"
version = "0.7.0"
edition = "2021"
description = "Open, reproducible calculation of assembly indices"
documentation = "https://docs.rs/assembly-theory"
readme = "README-crate.md"
repository = "https://github.com/DaymudeLab/assembly-theory"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.102"
bit-set = "0.10.0"
clap = { version = "4.6.1", features = ["derive"] }
csv = "1.4.0"
petgraph = "0.8.3"
pyo3 = { version = "0.29.0", features = ["abi3-py310", "extension-module"]}
rayon = "1.12.0"
dashmap = "6.2.1"
nauty-Traces-sys = "0.11.0"
bitvec = "1.0.1"
tokio = { version = "1.52.3", features = ["rt", "rt-multi-thread", "sync", "time"] }

[dev-dependencies]
criterion = "0.8.2"

[features]
default = ["python"]
python = []

[lib]
name = "assembly_theory"
path = "src/lib.rs"
crate-type = ["rlib","cdylib"]

[[bench]]
name = "benchmark"
harness = false

